### ISSUE TITLE
Drag line

### ISSUE THREAD

**Issue by kwnkouts** [plotly/react-cytoscapejs#10]
Hi, 
I would like to ask if it is possible, using this library, for the user to drag lines from a node to another in order to create the edges.
Thank you in advance!

**Comment by xhlulu** [comment]
It is likely possible to do so with the `cy` prop, but it will a fairly advanced usage, and the nodes will likely need to be immutable. Check out event listener in Cytoscape.js http://js.cytoscape.org/#core/events

**Comment by maxkfranz** [comment]
You can register extensions like edgehandles using the `cy` ref, as mentioned.
