### ISSUE TITLE
Canvas elements moved by 50% to the right of the CytoscapeComponent

### ISSUE THREAD

**Issue by wojciechteclaw** [plotly/react-cytoscapejs#112]
Hello everyone,
I tried to use cytoscape library instead of Force-graph-2d in my project. However, I have a problem because all canvas elements are moved exactly by 50% to the right of the correctly placed CytoscapeComponent. 
Do you have any advice on what I should change to have these elements aligned each other? 

`
    interface GraphProps {
        graphData: GraphData;
    }

    Cytoscape.use(COSEBilkent);
    const layout = { name: "cose-bilkent", idealEdgeLength: 200,  };

    const elements: Cytoscape.ElementDefinition[] = [
        { data: { id: "a" } },
        { data: { id: "b" } },
        { data: { id: "ab", label: "sample", source: "a", target: "b" } },
    ];

    const Graph: FC<GraphProps> = ({ graphData }) => {
        return (
            <div id="graph-element">
                <CytoscapeComponent
                    elements={elements}
                    layout={layout}
                    style={{ width: "600px", height: "600px"}}
                />
            </div>
        );
    };

    export { Graph };
`

![canvase_location](https://user-images.githubusercontent.com/57253397/216659195-fe24ff88-c19f-4f37-9522-d9a12697e188.png)
![main_div_in_component](https://user-images.githubusercontent.com/57253397/216659201-683c6ace-47d9-4ab1-8bbe-59455559d7a9.png)

**Comment by wojciechteclaw** [comment]
![canvase_location](https://user-images.githubusercontent.com/57253397/216659145-c4ca361e-2a8e-4622-8bff-049aec77f08d.png)
![main_div_in_component](https://user-images.githubusercontent.com/57253397/216659153-129e76ad-53c5-4db0-9e5a-e14f6dce455b.png)

**Comment by joshbernsteint** [comment]
Did you ever find a solution to this? I am struggling with this issue as well.

**Comment by wojciechteclaw** [comment]
Hello,

To be honest, I don’t remember what the solution was.

 

However, I would start with two points:

1.	Avoid using size expressed in pixels. I did it like this:
2.	        <div id="graph-element">
3.	            <CytoscapeComponent
4.	                elements={[]}
5.	                layout={graphLayoutConfiguration}
6.	                style={{
7.	                    width: “100%”,
8.	                    height: “100%”,
9.	                    margin: “0px auto”,
10.	                    display: “block”,
11.	                    backgroundColor: "#ced9d9",
12.	                }}

 

2) Check what is the display type of all parent components. I think this was relevant to the issue.

 

Cheers,

Wojciech

**Comment by joshbernsteint** [comment]
I figured out the issue. At least for me, I needed to set `text-align: left`. When I had it at center, that's what was causing the issue for me.

**Comment by wojciechteclaw** [comment]
Hi,
I think the problem in my cast was related to the `display` of parent components.
