### ISSUE TITLE
No option to rerun layout after adding new elements

### ISSUE THREAD

**Issue by alendit** [plotly/react-cytoscapejs#12]
Maybe I misunderstand it, but it seems to me that there is no way to rerun layout algorithms after when new elements get added/removed. 

Is this something you'd welcome a PR for?

**Comment by xhlulu** [comment]
It is possible to rerun it, using the `cy` handler. Here's what I'm using for Dash Cytoscape:
```JavaScript
    handleCy(cy) {
        ...
        // Refresh Layout if needed
        const refreshLayout = _.debounce(() => {
            const {
                autoRefreshLayout,
                layout
            } = this.props;

            if (autoRefreshLayout) {
                cy.layout(layout).run()
            }
        }, SELECT_THRESHOLD);

        cy.on('add remove', () => {
            refreshLayout();
        });
    }
```

where `autoRefreshLayout` is a prop indicating whether to refresh the layout or not when a new element is added. The function `handleCy()` is used specifically to handle the cy, which is passed in the `render()` method, which would look something like that:
```JavaScript
render() {
        const {
        ...
        } = this.props;

        return (
            <CytoscapeComponent
                cy={this.handleCy}
                elements={...}
                stylesheet={...}
            />
        )
    }
```

**Comment by xhlulu** [comment]
Note here I'm using lodash for the debounce method. Please check out the official docs, or the [react component for Dash Cytoscape ](https://github.com/plotly/dash-cytoscape/blob/master/src/lib/components/Cytoscape.react.js)

**Comment by maxkfranz** [comment]
This isn't possible to do declaratively, because each layout has a different set of options:  The diff would be handled differently in each case.  I suppose it could be supported for the simple `===` case, though that would have some caveats.

**Comment by invisibleroads** [comment]
@xhlulu 
Thank you sir! Your comment was a lifesaver.

**Comment by erikhofer** [comment]
Another option, if you don't want to use `debounce`, is using `useEffect` to re-run the layouts when elements change:

```ts
const elements = [ /* ... */ ]
const layout = { /* ... */ }

const [cy, setCy] = useState<Cytoscape.Core | null>(null)

useEffect(() => {
    cy?.layout(layout).run()
}, [cy, elements]) // make sur to add elements here

return <CytoscapeComponent cy={setCy} elements={elements} />
```
