### ISSUE TITLE
Question: Styling & Layout

### ISSUE THREAD

**Issue by ctrlaltaf** [plotly/react-cytoscapejs#123]
I am trying to generate a graph, where a node is labeled as the core node, and there will always be sub paths branching out of this code node (of varying lengths). Is there a layout out there that would do this, or if someone has some direction I would highly appreciate this. Below is a toddler sketch of what I am envisioning the graph to look like. Thank you!
<img width="538" alt="Screenshot 2023-09-22 at 10 18 22 AM" src="https://github.com/plotly/react-cytoscapejs/assets/67818840/58ada6d9-5664-4be9-b856-f228328c0754">

**Comment by snakeM** [comment]
Using the [concentric layout](https://js.cytoscape.org/#layouts/concentric) would probably be your best bet.
Demo: https://js.cytoscape.org/demos/concentric-layout/
