### ISSUE TITLE
[Question] Rendering options available in react?

### ISSUE THREAD

**Issue by xhlulu** [plotly/react-cytoscapejs#13]
Are the rendering options such as 
```
  // rendering options:
  headless: false,
  styleEnabled: true,
  hideEdgesOnViewport: false,
  hideLabelsOnViewport: false,
  textureOnViewport: false,
  motionBlur: false,
  motionBlurOpacity: 0.2,
  wheelSensitivity: 1,
  pixelRatio: 'auto'
```

available as props in the react component? I.e., the ones decribed here: http://js.cytoscape.org/#core/initialisation

**Comment by maxkfranz** [comment]
They could be supported, but they wouldn't be mutable without creating an entirely new `cy` instance.  The library does not allow for changing those options.

**Comment by xhlulu** [comment]
Hmm that makes sense! Thanks for the heads up.
