### ISSUE TITLE
Add update callback?

### ISSUE THREAD

**Issue by Secretmapper** [plotly/react-cytoscapejs#14]
When the graph is edited (i.e. a node is moved) the passed props never changes in the parent.

Perhaps there can be a `onElementChange` callback so that the parent can update the elements state

**Comment by maxkfranz** [comment]
That's what the general `cy` prop is for.  You can set up arbitrary listeners with a `cy` ref.

**Comment by xhlulu** [comment]
Max's answer is great. I use this prop in this example: https://github.com/plotly/dash-cytoscape/blob/master/src/lib/components/Cytoscape.react.js

**Comment by Secretmapper** [comment]
Thanks for the feedback! I am currently doing something [similar](https://github.com/Secretmapper/webflap/blob/fc22dc6807c7c83be093f7f983d9d39ae2ca876e/src/automata/Editor/index.js#L103) in my project, attaching listeners on the cy instance

My thoughts on creating this issue was actually to allow insertion of listeners in more idiomatic React, like for example:

> <Cytoscape
>   onTap={onCytoscapeTap}
>   onNodeCreate={onNodeCreate}
>   onEdgeCreate={onEdgeCreate}
> />

However, after investigating the cytoscape API more closely, I have realized that this is tricky to generalize as cytoscape supports arbitrary selectors (i.e. `node.dfa__state`).

In that light I agree that it might be best to just let the listeners be handled 'manually' as the node/edge data are not created using JSX components.
