### ISSUE TITLE
Using cy.on()

### ISSUE THREAD

**Issue by aoisun** [plotly/react-cytoscapejs#19]
Hi.
I started using this react-component.
The question is how can I use cy.on() for setting my own action for 'click' on nodes/edges?
I have this code and try using "cy.on()" from http://js.cytoscape.org/#core/events 
Any advice?

`<CytoscapeComponent                    
elements={elements}
                    style={style}
                    stylesheet={stylesheet}
                    cy={cy => this.cy = cy}
                />`

**Comment by maxkfranz** [comment]
Use the `cy` ref.
