### ISSUE TITLE
"Uncaught ReferenceError: cy is not defined"

### ISSUE THREAD

**Issue by scottc11** [plotly/react-cytoscapejs#27]
I cannot access the underlying Cytoscape instance via Reacts ref API. I get the following error in the console -> `Uncaught ReferenceError: cy is not defined`

```
class Container extends React.Component {
  constructor(props) {
    super(props);
    this.cy;
  }

  componentDidUpdate() {
    console.log(this.cy);
  }

  render() {
    return <CytoscapeComponent cy={ (cy) = this.cy = cy } elements={mockData} style={ { width: '600px', height: '600px' } } />;
  }
}

ReactDOM.render(<Container />, document.querySelector('#container'));
```

Upon inspecting the `component.js` file, I don't see any of the suggested syntax found [in the React Docs](https://reactjs.org/docs/forwarding-refs.html).  Am I doing something wrong?

**Comment by Remimstr** [comment]
The error is in the way you're using the cy prop. It expects a function, so you should do:
`cy = { cy => this.cy = cy }`

instead of:
`cy = { cy = this.cy = cy }`

**Comment by scottc11** [comment]
:man-facepalming:

**Comment by daphnie-el** [comment]
Did you find a solution to this problem. I am currently facing it and its preventing me from making a PR
