### ISSUE TITLE
[Discussion] Good practice for event handling

### ISSUE THREAD

**Issue by xhlulu** [plotly/react-cytoscapejs#4]
Is there event handler for this react wrapper? 

In cytoscape.js events are handled in a jquery manner: http://js.cytoscape.org/#events

However, event handling in react is quite different. For example, we would use props such as `onTap`, `onClick`, etc. which are fired when the corresponding event happens. Should those props be added, or should we use the `cy.on()` to handle those events?

**Comment by Spaxe** [comment]
Was there a conclusion to this discussion?

**Comment by k8reindeer** [comment]
I'm also interested in learning how this turned out?
