### ISSUE TITLE
Last version from NPM isn't the last one ?

### ISSUE THREAD

**Issue by Toukassay** [plotly/react-cytoscapejs#94]
Hello,

I've follow the installation process via npm : `npm install react-cytoscapejs` but it seems that it didn't retrieve the very last version... Looking in the package-lock.json and downloading from https://registry.npmjs.org/react-cytoscapejs/-/react-cytoscapejs-1.2.1.tgz, you'll see that, for example in `src/component.js` the downloaded file doesn't contain your commit about using ref at line 47..
It's the first time I experienced this, doing the npm install and don't get the very last version.
Am I doing things wrong ?

**Comment by Toukassay** [comment]
Temporary fixed by using : `npm i git+https://github.com/plotly/react-cytoscapejs`

**Comment by alexcjohnson** [comment]
Sorry about the delay here - I'm not sure what went wrong with v1.2.1, but I've confirmed that v2.0.0 (published last week) contains all the correct code.
